name: build

on: pull_request

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      id: versions
      run: |
        echo ::set-output name=go::$(grep '^FROM go' .github/go/Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
        echo "Using Go version ${{ steps.versions.outputs.go }}"
    -
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ steps.versions.outputs.go }}
    -
      name: Build
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: build --config=.github/goreleaser.yml --snapshot
