name: release

on:
  push:
    branches:
    - master
    - main

jobs:

  tag:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v4
    -
      uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  goreleaser:
    runs-on: ubuntu-latest
    needs: tag
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Unshallow
      run: git fetch --prune --unshallow
    -
      id: versions
      run: |
        echo ::set-output name=go::$(grep '^FROM go' .github/go/Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
        echo "Using Go version ${{ steps.versions.outputs.go }}"
    -
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ steps.versions.outputs.go }}
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Release
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --config=.github/goreleaser.yml --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
