name: tag

on:
  push:
    branches:
    - master
    - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
